package rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RName implements java.io.Serializable {
  public abstract <R,A> R accept(RName.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rhocomb.Absyn.RQuot p, A arg);

  }

}
