package rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RQuot  extends RName {
  public final RProc rproc_;
  public RQuot(RProc p1) { rproc_ = p1; }

  public <R,A> R accept(rhocomb.Absyn.RName.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rhocomb.Absyn.RQuot) {
      rhocomb.Absyn.RQuot x = (rhocomb.Absyn.RQuot)o;
      return this.rproc_.equals(x.rproc_);
    }
    return false;
  }

  public int hashCode() {
    return this.rproc_.hashCode();
  }


}
