package rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RSeq  extends RComb {
  public final RName rname_1, rname_2, rname_3;
  public RSeq(RName p1, RName p2, RName p3) { rname_1 = p1; rname_2 = p2; rname_3 = p3; }

  public <R,A> R accept(rhocomb.Absyn.RComb.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rhocomb.Absyn.RSeq) {
      rhocomb.Absyn.RSeq x = (rhocomb.Absyn.RSeq)o;
      return this.rname_1.equals(x.rname_1) && this.rname_2.equals(x.rname_2) && this.rname_3.equals(x.rname_3);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.rname_1.hashCode())+this.rname_2.hashCode())+this.rname_3.hashCode();
  }


}
