package picomb.Absyn; // Java Package generated by the BNF Converter.

public class NVar  extends YName {
  public final String cvar_;
  public NVar(String p1) { cvar_ = p1; }

  public <R,A> R accept(picomb.Absyn.YName.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof picomb.Absyn.NVar) {
      picomb.Absyn.NVar x = (picomb.Absyn.NVar)o;
      return this.cvar_.equals(x.cvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.cvar_.hashCode();
  }


}
