package picomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class YComb implements java.io.Serializable {
  public abstract <R,A> R accept(YComb.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(picomb.Absyn.YZero p, A arg);
    public R visit(picomb.Absyn.YMsg p, A arg);
    public R visit(picomb.Absyn.YKill p, A arg);
    public R visit(picomb.Absyn.YDup p, A arg);
    public R visit(picomb.Absyn.YSeq p, A arg);
    public R visit(picomb.Absyn.YFwd p, A arg);
    public R visit(picomb.Absyn.YBrl p, A arg);
    public R visit(picomb.Absyn.YBrr p, A arg);

  }

}
