package picomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class YName implements java.io.Serializable {
  public abstract <R,A> R accept(YName.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(picomb.Absyn.NWild p, A arg);
    public R visit(picomb.Absyn.NVar p, A arg);

  }

}
