package picomb.Absyn; // Java Package generated by the BNF Converter.

public class YSeq  extends YComb {
  public final YName yname_1, yname_2, yname_3;
  public YSeq(YName p1, YName p2, YName p3) { yname_1 = p1; yname_2 = p2; yname_3 = p3; }

  public <R,A> R accept(picomb.Absyn.YComb.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof picomb.Absyn.YSeq) {
      picomb.Absyn.YSeq x = (picomb.Absyn.YSeq)o;
      return this.yname_1.equals(x.yname_1) && this.yname_2.equals(x.yname_2) && this.yname_3.equals(x.yname_3);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.yname_1.hashCode())+this.yname_2.hashCode())+this.yname_3.hashCode();
  }


}
