package picomb.Absyn; // Java Package generated by the BNF Converter.

public class YStr  extends YProc {
  public final YProc yproc_;
  public YStr(YProc p1) { yproc_ = p1; }

  public <R,A> R accept(picomb.Absyn.YProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof picomb.Absyn.YStr) {
      picomb.Absyn.YStr x = (picomb.Absyn.YStr)o;
      return this.yproc_.equals(x.yproc_);
    }
    return false;
  }

  public int hashCode() {
    return this.yproc_.hashCode();
  }


}
