package picomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class YVar implements java.io.Serializable {
  public abstract <R,A> R accept(YVar.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(picomb.Absyn.YWild p, A arg);
    public R visit(picomb.Absyn.YVVar p, A arg);

  }

}
