package picomb.Absyn; // Java Package generated by the BNF Converter.

public class YBrl  extends YComb {
  public final YName yname_1, yname_2;
  public YBrl(YName p1, YName p2) { yname_1 = p1; yname_2 = p2; }

  public <R,A> R accept(picomb.Absyn.YComb.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof picomb.Absyn.YBrl) {
      picomb.Absyn.YBrl x = (picomb.Absyn.YBrl)o;
      return this.yname_1.equals(x.yname_1) && this.yname_2.equals(x.yname_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.yname_1.hashCode())+this.yname_2.hashCode();
  }


}
