package picomb.Absyn; // Java Package generated by the BNF Converter.

public class YInj  extends YProc {
  public final YComb ycomb_;
  public YInj(YComb p1) { ycomb_ = p1; }

  public <R,A> R accept(picomb.Absyn.YProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof picomb.Absyn.YInj) {
      picomb.Absyn.YInj x = (picomb.Absyn.YInj)o;
      return this.ycomb_.equals(x.ycomb_);
    }
    return false;
  }

  public int hashCode() {
    return this.ycomb_.hashCode();
  }


}
