package picomb.Absyn; // Java Package generated by the BNF Converter.

public class YKill  extends YComb {
  public final YName yname_;
  public YKill(YName p1) { yname_ = p1; }

  public <R,A> R accept(picomb.Absyn.YComb.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof picomb.Absyn.YKill) {
      picomb.Absyn.YKill x = (picomb.Absyn.YKill)o;
      return this.yname_.equals(x.yname_);
    }
    return false;
  }

  public int hashCode() {
    return this.yname_.hashCode();
  }


}
