package picomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class YProc implements java.io.Serializable {
  public abstract <R,A> R accept(YProc.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(picomb.Absyn.YInj p, A arg);
    public R visit(picomb.Absyn.YStr p, A arg);
    public R visit(picomb.Absyn.YNew p, A arg);
    public R visit(picomb.Absyn.YPar p, A arg);

  }

}
