package rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RBrr  extends RComb {
  public final RName rname_1, rname_2;
  public RBrr(RName p1, RName p2) { rname_1 = p1; rname_2 = p2; }

  public <R,A> R accept(rhocomb.Absyn.RComb.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rhocomb.Absyn.RBrr) {
      rhocomb.Absyn.RBrr x = (rhocomb.Absyn.RBrr)o;
      return this.rname_1.equals(x.rname_1) && this.rname_2.equals(x.rname_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.rname_1.hashCode())+this.rname_2.hashCode();
  }


}
