package rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RComb implements java.io.Serializable {
  public abstract <R,A> R accept(RComb.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rhocomb.Absyn.RZero p, A arg);
    public R visit(rhocomb.Absyn.RMsg p, A arg);
    public R visit(rhocomb.Absyn.RKill p, A arg);
    public R visit(rhocomb.Absyn.RDup p, A arg);
    public R visit(rhocomb.Absyn.RSeq p, A arg);
    public R visit(rhocomb.Absyn.RFwd p, A arg);
    public R visit(rhocomb.Absyn.RBrl p, A arg);
    public R visit(rhocomb.Absyn.RBrr p, A arg);

  }

}
