package rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RKill  extends RComb {
  public final RName rname_;
  public RKill(RName p1) { rname_ = p1; }

  public <R,A> R accept(rhocomb.Absyn.RComb.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rhocomb.Absyn.RKill) {
      rhocomb.Absyn.RKill x = (rhocomb.Absyn.RKill)o;
      return this.rname_.equals(x.rname_);
    }
    return false;
  }

  public int hashCode() {
    return this.rname_.hashCode();
  }


}
