package rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RProc implements java.io.Serializable {
  public abstract <R,A> R accept(RProc.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(rhocomb.Absyn.RInj p, A arg);
    public R visit(rhocomb.Absyn.RStr p, A arg);
    public R visit(rhocomb.Absyn.RPar p, A arg);

  }

}
