package rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RZero  extends RComb {
  public RZero() { }

  public <R,A> R accept(rhocomb.Absyn.RComb.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof rhocomb.Absyn.RZero) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
