package asyncpi.Absyn; // Java Package generated by the BNF Converter.

public class NVar  extends PName {
  public final String var_;
  public NVar(String p1) { var_ = p1; }

  public <R,A> R accept(asyncpi.Absyn.PName.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof asyncpi.Absyn.NVar) {
      asyncpi.Absyn.NVar x = (asyncpi.Absyn.NVar)o;
      return this.var_.equals(x.var_);
    }
    return false;
  }

  public int hashCode() {
    return this.var_.hashCode();
  }


}
