package asyncpi.Absyn; // Java Package generated by the BNF Converter.

public abstract class PComp implements java.io.Serializable {
  public abstract <R,A> R accept(PComp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(asyncpi.Absyn.PZero p, A arg);
    public R visit(asyncpi.Absyn.PInp p, A arg);
    public R visit(asyncpi.Absyn.POutp p, A arg);

  }

}
