package asyncpi.Absyn; // Java Package generated by the BNF Converter.

public abstract class PName implements java.io.Serializable {
  public abstract <R,A> R accept(PName.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(asyncpi.Absyn.NWild p, A arg);
    public R visit(asyncpi.Absyn.NVar p, A arg);

  }

}
