package asyncpi.Absyn; // Java Package generated by the BNF Converter.

public class PNew  extends PProc {
  public final ListPName listpname_;
  public final PProc pproc_;
  public PNew(ListPName p1, PProc p2) { listpname_ = p1; pproc_ = p2; }

  public <R,A> R accept(asyncpi.Absyn.PProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof asyncpi.Absyn.PNew) {
      asyncpi.Absyn.PNew x = (asyncpi.Absyn.PNew)o;
      return this.listpname_.equals(x.listpname_) && this.pproc_.equals(x.pproc_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listpname_.hashCode())+this.pproc_.hashCode();
  }


}
