package asyncpi.Absyn; // Java Package generated by the BNF Converter.

public class POutp  extends PComp {
  public final PName pname_1, pname_2;
  public POutp(PName p1, PName p2) { pname_1 = p1; pname_2 = p2; }

  public <R,A> R accept(asyncpi.Absyn.PComp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof asyncpi.Absyn.POutp) {
      asyncpi.Absyn.POutp x = (asyncpi.Absyn.POutp)o;
      return this.pname_1.equals(x.pname_1) && this.pname_2.equals(x.pname_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pname_1.hashCode())+this.pname_2.hashCode();
  }


}
