package asyncpi.Absyn; // Java Package generated by the BNF Converter.

public abstract class PProc implements java.io.Serializable {
  public abstract <R,A> R accept(PProc.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(asyncpi.Absyn.PInj p, A arg);
    public R visit(asyncpi.Absyn.PRep p, A arg);
    public R visit(asyncpi.Absyn.PNew p, A arg);
    public R visit(asyncpi.Absyn.PPar p, A arg);

  }

}
