package asyncpi.Absyn; // Java Package generated by the BNF Converter.

public abstract class PVar implements java.io.Serializable {
  public abstract <R,A> R accept(PVar.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(asyncpi.Absyn.PWild p, A arg);
    public R visit(asyncpi.Absyn.PVVar p, A arg);

  }

}
