package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCPInp  extends RCPComp {
  public final RCUName rcuname_1, rcuname_2;
  public final RCPProc rcpproc_;
  public RCPInp(RCUName p1, RCUName p2, RCPProc p3) { rcuname_1 = p1; rcuname_2 = p2; rcpproc_ = p3; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPComp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPInp) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPInp x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPInp)o;
      return this.rcuname_1.equals(x.rcuname_1) && this.rcuname_2.equals(x.rcuname_2) && this.rcpproc_.equals(x.rcpproc_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.rcuname_1.hashCode())+this.rcuname_2.hashCode())+this.rcpproc_.hashCode();
  }


}
