package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCPInj  extends RCPProc {
  public final RCPComp rcpcomp_;
  public RCPInj(RCPComp p1) { rcpcomp_ = p1; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPInj) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPInj x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPInj)o;
      return this.rcpcomp_.equals(x.rcpcomp_);
    }
    return false;
  }

  public int hashCode() {
    return this.rcpcomp_.hashCode();
  }


}
