package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCPNVar  extends RCPName {
  public final String var_;
  public RCPNVar(String p1) { var_ = p1; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPName.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPNVar) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPNVar x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPNVar)o;
      return this.var_.equals(x.var_);
    }
    return false;
  }

  public int hashCode() {
    return this.var_.hashCode();
  }


}
