package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCPNew  extends RCPProc {
  public final ListRCPName listrcpname_;
  public final RCPProc rcpproc_;
  public RCPNew(ListRCPName p1, RCPProc p2) { listrcpname_ = p1; rcpproc_ = p2; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPNew) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPNew x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPNew)o;
      return this.listrcpname_.equals(x.listrcpname_) && this.rcpproc_.equals(x.rcpproc_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listrcpname_.hashCode())+this.rcpproc_.hashCode();
  }


}
