package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCPOutp  extends RCPComp {
  public final RCPName rcpname_1, rcpname_2;
  public RCPOutp(RCPName p1, RCPName p2) { rcpname_1 = p1; rcpname_2 = p2; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPComp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPOutp) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPOutp x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPOutp)o;
      return this.rcpname_1.equals(x.rcpname_1) && this.rcpname_2.equals(x.rcpname_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.rcpname_1.hashCode())+this.rcpname_2.hashCode();
  }


}
