package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RCPProc implements java.io.Serializable {
  public abstract <R,A> R accept(RCPProc.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPInj p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPRep p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPNew p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPPar p, A arg);

  }

}
