package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCPPar  extends RCPProc {
  public final RCPProc rcpproc_1, rcpproc_2;
  public RCPPar(RCPProc p1, RCPProc p2) { rcpproc_1 = p1; rcpproc_2 = p2; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPPar) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPPar x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPPar)o;
      return this.rcpproc_1.equals(x.rcpproc_1) && this.rcpproc_2.equals(x.rcpproc_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.rcpproc_1.hashCode())+this.rcpproc_2.hashCode();
  }


}
