package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RCPVar implements java.io.Serializable {
  public abstract <R,A> R accept(RCPVar.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPPWild p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPPVVar p, A arg);

  }

}
