package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCRStr  extends RCRProc {
  public final RCRName rcrname_;
  public RCRStr(RCRName p1) { rcrname_ = p1; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRStr) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRStr x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRStr)o;
      return this.rcrname_.equals(x.rcrname_);
    }
    return false;
  }

  public int hashCode() {
    return this.rcrname_.hashCode();
  }


}
