package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCYBrl  extends RCYComb {
  public final RCUName rcuname_1, rcuname_2;
  public RCYBrl(RCUName p1, RCUName p2) { rcuname_1 = p1; rcuname_2 = p2; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYComb.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYBrl) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYBrl x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYBrl)o;
      return this.rcuname_1.equals(x.rcuname_1) && this.rcuname_2.equals(x.rcuname_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.rcuname_1.hashCode())+this.rcuname_2.hashCode();
  }


}
