package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RCYComb implements java.io.Serializable {
  public abstract <R,A> R accept(RCYComb.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYZero p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYMsg p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYKill p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYDup p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYSeq p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYFwd p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYBrl p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYBrr p, A arg);

  }

}
