package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCYNVar  extends RCYName {
  public final String cvar_;
  public RCYNVar(String p1) { cvar_ = p1; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYName.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYNVar) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYNVar x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYNVar)o;
      return this.cvar_.equals(x.cvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.cvar_.hashCode();
  }


}
