package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCYPar  extends RCYProc {
  public final RCYProc rcyproc_1, rcyproc_2;
  public RCYPar(RCYProc p1, RCYProc p2) { rcyproc_1 = p1; rcyproc_2 = p2; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYPar) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYPar x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYPar)o;
      return this.rcyproc_1.equals(x.rcyproc_1) && this.rcyproc_2.equals(x.rcyproc_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.rcyproc_1.hashCode())+this.rcyproc_2.hashCode();
  }


}
