package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RqEval  extends Req {
  public final RCRProc rcrproc_;
  public RqEval(RCRProc p1) { rcrproc_ = p1; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.Req.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RqEval) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RqEval x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RqEval)o;
      return this.rcrproc_.equals(x.rcrproc_);
    }
    return false;
  }

  public int hashCode() {
    return this.rcrproc_.hashCode();
  }


}
