package asyncpi.Absyn; // Java Package generated by the BNF Converter.

public class PPar  extends PProc {
  public final PProc pproc_1, pproc_2;
  public PPar(PProc p1, PProc p2) { pproc_1 = p1; pproc_2 = p2; }

  public <R,A> R accept(asyncpi.Absyn.PProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof asyncpi.Absyn.PPar) {
      asyncpi.Absyn.PPar x = (asyncpi.Absyn.PPar)o;
      return this.pproc_1.equals(x.pproc_1) && this.pproc_2.equals(x.pproc_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pproc_1.hashCode())+this.pproc_2.hashCode();
  }


}
