package asyncpi.Absyn; // Java Package generated by the BNF Converter.

public class PRep  extends PProc {
  public final PProc pproc_;
  public PRep(PProc p1) { pproc_ = p1; }

  public <R,A> R accept(asyncpi.Absyn.PProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof asyncpi.Absyn.PRep) {
      asyncpi.Absyn.PRep x = (asyncpi.Absyn.PRep)o;
      return this.pproc_.equals(x.pproc_);
    }
    return false;
  }

  public int hashCode() {
    return this.pproc_.hashCode();
  }


}
