package asyncpi.Absyn; // Java Package generated by the BNF Converter.

public class PVVar  extends PVar {
  public final String var_;
  public PVVar(String p1) { var_ = p1; }

  public <R,A> R accept(asyncpi.Absyn.PVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof asyncpi.Absyn.PVVar) {
      asyncpi.Absyn.PVVar x = (asyncpi.Absyn.PVVar)o;
      return this.var_.equals(x.var_);
    }
    return false;
  }

  public int hashCode() {
    return this.var_.hashCode();
  }


}
