package asyncpi.Absyn; // Java Package generated by the BNF Converter.

public class PZero  extends PComp {
  public PZero() { }

  public <R,A> R accept(asyncpi.Absyn.PComp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof asyncpi.Absyn.PZero) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
