package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RCPComp implements java.io.Serializable {
  public abstract <R,A> R accept(RCPComp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPZero p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPInp p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPOutp p, A arg);

  }

}
