package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RCPName implements java.io.Serializable {
  public abstract <R,A> R accept(RCPName.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPNWild p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCPNVar p, A arg);

  }

}
