package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RCRComb implements java.io.Serializable {
  public abstract <R,A> R accept(RCRComb.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRZero p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRMsg p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRKill p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRDup p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRSeq p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRFwd p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRBrl p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRBrr p, A arg);

  }

}
