package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCRInj  extends RCRProc {
  public final RCRComb rcrcomb_;
  public RCRInj(RCRComb p1) { rcrcomb_ = p1; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRInj) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRInj x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRInj)o;
      return this.rcrcomb_.equals(x.rcrcomb_);
    }
    return false;
  }

  public int hashCode() {
    return this.rcrcomb_.hashCode();
  }


}
