package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCRPar  extends RCRProc {
  public final RCRProc rcrproc_1, rcrproc_2;
  public RCRPar(RCRProc p1, RCRProc p2) { rcrproc_1 = p1; rcrproc_2 = p2; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRPar) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRPar x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRPar)o;
      return this.rcrproc_1.equals(x.rcrproc_1) && this.rcrproc_2.equals(x.rcrproc_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.rcrproc_1.hashCode())+this.rcrproc_2.hashCode();
  }


}
