package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RCRProc implements java.io.Serializable {
  public abstract <R,A> R accept(RCRProc.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRInj p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRStr p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRPar p, A arg);

  }

}
