package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCRZero  extends RCRComb {
  public RCRZero() { }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRComb.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCRZero) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
