package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RCUName implements java.io.Serializable {
  public abstract <R,A> R accept(RCUName.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCUNWild p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCUNVar p, A arg);

  }

}
