package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCYInj  extends RCYProc {
  public final RCYComb rcycomb_;
  public RCYInj(RCYComb p1) { rcycomb_ = p1; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYInj) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYInj x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYInj)o;
      return this.rcycomb_.equals(x.rcycomb_);
    }
    return false;
  }

  public int hashCode() {
    return this.rcycomb_.hashCode();
  }


}
