package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RCYName implements java.io.Serializable {
  public abstract <R,A> R accept(RCYName.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYNWild p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYNVar p, A arg);

  }

}
