package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCYNew  extends RCYProc {
  public final ListRCYName listrcyname_;
  public final RCYProc rcyproc_;
  public RCYNew(ListRCYName p1, RCYProc p2) { listrcyname_ = p1; rcyproc_ = p2; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYProc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYNew) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYNew x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYNew)o;
      return this.listrcyname_.equals(x.listrcyname_) && this.rcyproc_.equals(x.rcyproc_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listrcyname_.hashCode())+this.rcyproc_.hashCode();
  }


}
