package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCYNWild  extends RCYName {
  public RCYNWild() { }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYName.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYNWild) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
