package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class RCYProc implements java.io.Serializable {
  public abstract <R,A> R accept(RCYProc.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYInj p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYStr p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYNew p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYPar p, A arg);

  }

}
