package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RCYSeq  extends RCYComb {
  public final RCUName rcuname_1, rcuname_2, rcuname_3;
  public RCYSeq(RCUName p1, RCUName p2, RCUName p3) { rcuname_1 = p1; rcuname_2 = p2; rcuname_3 = p3; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYComb.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYSeq) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYSeq x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RCYSeq)o;
      return this.rcuname_1.equals(x.rcuname_1) && this.rcuname_2.equals(x.rcuname_2) && this.rcuname_3.equals(x.rcuname_3);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.rcuname_1.hashCode())+this.rcuname_2.hashCode())+this.rcuname_3.hashCode();
  }


}
