package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public abstract class Req implements java.io.Serializable {
  public abstract <R,A> R accept(Req.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RqP2R p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RqY2R p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RqP2Y p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RqEval p, A arg);
    public R visit(coop.rchain.rhocomb.pi2rhocomb.Absyn.RqCmd p, A arg);

  }

}
