package coop.rchain.rhocomb.pi2rhocomb.Absyn; // Java Package generated by the BNF Converter.

public class RqP2R  extends Req {
  public final RCPProc rcpproc_;
  public RqP2R(RCPProc p1) { rcpproc_ = p1; }

  public <R,A> R accept(coop.rchain.rhocomb.pi2rhocomb.Absyn.Req.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof coop.rchain.rhocomb.pi2rhocomb.Absyn.RqP2R) {
      coop.rchain.rhocomb.pi2rhocomb.Absyn.RqP2R x = (coop.rchain.rhocomb.pi2rhocomb.Absyn.RqP2R)o;
      return this.rcpproc_.equals(x.rcpproc_);
    }
    return false;
  }

  public int hashCode() {
    return this.rcpproc_.hashCode();
  }


}
